[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "b4n1-boost"
version = "0.1.6"
description = "B4N1-BOOST — Transparent middleware accelerator for Django, FastAPI and Flask"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "BSL-1.1"}
authors = [
    {name = "Bani Montoya", email = "banimontoya@gmail.com"}
]

[tool.setuptools.packages.find]
where = ["."]
include = ["b4n1_boost*"]

